name: Checkov Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkov-scan:
    name: Checkov Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Checkov
        run: pip install checkov

      # Passo 2: Executar Checkov com output SARIF
      - name: Run Checkov and generate SARIF report
        run: |
          checkov -d ./ \
            -o sarif \
            --output-file checkov-results.sarif \
            --quiet

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov-results.sarif

      - name: Show Checkov results (verbose)
        run: checkov -d ./
