on:
  issues:
    types: [opened]
name: Issues
jobs:
  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        uses: step-security/assign-author@v1
